### ISSUE TITLE
Position of Appbar is incorrect

### ISSUE THREAD

**Issue by Azarnoyz** [shivathapaa/SocialDemoProjects#1]
Hi, I have an issue, when I tried to use it, the start position of appbar is not below status bar, its under status bar, how to fix it?
Pixel 7, android 14

The green one is appbar
![share_3073518684869093777](https://github.com/user-attachments/assets/e7adc946-1f68-451e-93ad-2319ec8c7414)

**Comment by shivathapaa** [comment]
## Case 1 (Use Scaffold): If you are using Scaffold() then it will handle padding by itself.

```kotlin
    Scaffold(
        topBar = {
            CustomFlexibleTopAppBar() {
                // Your component goes here
            }
    ) { paddingValues->
        // Body comonents
    }
```

## Case 2 (Using .statusBarsPadding() modifier): To have top padding of status bar you should use .statusBarsPadding() modifier to the top first component.

```kotlin
    Scaffold(
        topBar = {
            CustomFlexibleTopAppBar(
                modifier = Modifier.statusBarsPadding()
            ) {
                // Or, add statusBarsPadding() modifier to its child components as per your design requirement
                Column(modifier = Modifier.statusBarsPadding()) { ... }
                // Your component goes here
            }
    ) { paddingValues->
        // Body comonents
    }
```

Let me know if that works! :)

**Comment by Azarnoyz** [comment]
Case 2 is working, thank you :)

**Comment by Azarnoyz** [comment]
Scaffold(
        topBar = {
       
                FlexibleTopBar(
                    modifier = Modifier.statusBarsPadding(),
                    scrollBehavior = topAppBarScrollBehavior,
                    content = {}
                    
                    }
